kind = "api"
previewPath = "/"
title = "EMOG Web App"
version = "1.0.0"
id = "3B4_FFSkEVBkAeYMFRJ2e"

[[services]]
localPort = 5000
name = "EMOG Web App"
paths = ["/"]

[services.development]
run = "cd ../.. && python manage.py runserver 0.0.0.0:5000"

[services.production]

[services.production.run]
args = ["sh", "-c", "cd ../.. && python manage.py runserver 0.0.0.0:5000"]

[services.production.health.startup]
path = "/"
